Hw6 hotel
AlexChampi/Kotlin-Hw pull request #10
Opened 2022-04-04 03:09 UTC by AlexChampi

2022-04-04 16:45 UTC, mplain requested changes

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/HotelController.kt
> +    @GetMapping("/check-in")
по стандарту REST, GET-методы ни в коем случае не должны ничего изменять. они должны только предоставлять информацию, и должны быть идемпотентными - то есть сколько раз ни запрашивай, возвращать должны одно и то же (если конечно не было параллельных изменений в базе)

если твой эндпоинт вносит какие-то изменения в приложение или базу, переделай из GET на POST

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/Reception.kt
> +        val result = setOfRoom.find { it.type == type && it.status == "free" } ?: return Room(null, null, null, null)
очень затратно получать полный список комнат и фильтровать на уровне сервиса

реальное приложение так работать не имеет право

фильтрация по параметрам должна происходить уже в базе / в стороннем сервисе, куда ты ходишь за данными

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/Reception.kt
> +        return result
ты поменял в ответе статус, а в базе поменял?

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/Reception.kt
> +        room.status = "free"
ты поменял в ответе статус, а в базе поменял?

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/model/Room.kt
> +    var status: String?
в котлине очень стараемся работать с иммутабельными структурами данных, не используем var

вместо `room.status = "free"` пишем `val newRoom = room.copy(status = "free")`

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/Reception.kt
> +        val result = setOfRoom.find { it.type == type && it.status == "free" } ?: return Room(null, null, null, null)
структурируй код так, чтобы в функции был только один return

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/Reception.kt
> +        val result = setOfRoom.find { it.type == type && it.status == "free" } ?: return Room(null, null, null, null)
что означает возврат объекта Room с нуллами? ночуйте в хлеву? :) наверное в этом случае (если подходящих свободных комнат нету) нужно кидать ошибку

2022-04-04 16:45 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/model/Room.kt
> +    val number: Int?,
если аргумент в конструкторе нуллабельный, стоит проставить дефолтом нулл, чтобы проще было создавать объект

с другой стороны полагаю что здесь все поля должны быть обязательными (когда объект Room есть, а внутри него все поля пустые, это бессмыслица какая-то)

2022-04-05 06:36 UTC, mplain requested changes

2022-04-05 06:36 UTC, mplain commented on src/test/resources/application.yaml
> +server.port: 4000
очень странно, что в тестах у тебя не такой порт, как в мейне

для этого должно быть какое-то обоснование

настолько неочевидно и непонятно зачем, что кто-то когда-то обязательно об это споктнется

2022-04-09 09:51 UTC, mplain requested changes

2022-04-09 09:51 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/RoomClient.kt
> +        val response = restTemplate.getForEntity<Set<Room?>>(
нельзя использовать getForEntity для получения списка (или любого сложного дженерика), я писал об этом в чате. в рантаймеу тебя на руках Set<LinkedMap<String, Any?>

используй метод exchange

2022-04-09 09:51 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/RoomClient.kt
> +        val url = "$roomAddress$/room/$number"
переиспользуй GET_ROOM_BY_NUMBER

2022-04-09 09:51 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/RoomClient.kt
> +        val url = "$roomAddress$/room/$number"
переиспользуй GET_ROOM_BY_NUMBER

2022-04-09 09:51 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/RoomClient.kt
> +    fun checkIn(number: Int, room: Room) {
checkIn и checkOut должны быть реализованы на уровне сервиса, а в клиенте должен быть единый метод put / patch/ update/ chargeStatus

2022-04-09 09:51 UTC, mplain commented on src/main/resources/application.yaml
> +room.address: http://localhost:5001
реализуй в отдельном пакете room функционал другого приложение:
- RoomController
- RoomService (возможно, если нужен)
- RoomDao (реализация взаимодействия с базой данных, в твоем случае это сервис с мапой, в следующей домашке заменишь на реализации подключения к реальной бд, в тестах этот класс соответственно будет мокироваться)

2022-04-10 09:01 UTC, mplain requested changes

2022-04-10 09:01 UTC, mplain commented on build.gradle.kts
> +    google()
а для чего тебе гугловский репозиторий?

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/Reception.kt
> +        return result as Set<Room>
кастование сразу значит, что что-то идет не так как должно

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    fun getRoomByType(@RequestParam type: String): Set<Room> =
пусть это будет общий поисковый эндпоинт

GET /room?type=xxx

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    fun getRoom(@RequestParam number: Int): Room =
а это запрос по уникальному идентификатору

GET /room/{number}

и используй @PathVariable вместо @RequestParam

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    fun changeStatus(@RequestBody room: Room, @RequestParam newStatus: String) {
тут у тебя перемешалось

PUT принимает готовый объект в теле
```
@PutMapping
fun updateRoom(@RequestBody room: Room)
```

PATCH принимает уникальный идентификатор объекта и параметры, которые нужно изменить
```
@PatchMapping("/{number}")
fun changeStatus(@PathVariable number: Int, @RequestParam status: String)
```
здесь наверное лучше второй вариант

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/service/client/RoomClient.kt
> +    private val roomDAO: RoomDAO,
клиент и дао - это сущности одного порядка, они не должны перевызывать друг друга, это терминальные точки выхода из приложения

откажить от этого класса вообще, и в RoomService укажи прямую зависимость на RoomDao

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/service/client/RoomDAO.kt
> +class RoomDAO(
аббревиатуры тоже лучше писать камелКейсом: roomDao: RoomDao

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/Reception.kt
> +        //requireNotNull(room) { "No available room" }
таки requireNotNull с понятным сообщением лучше чем !!

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/ReceptionClient.kt
> +class ReceptionClient(
клиент - это не ЧЕЙ клиент, а это КУДА клиент

имя клиента должно указывать на то, КУДА он ходит, а не ОТКУДА

это у тебя RoomClient

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/ReceptionClient.kt
> +        "$roomAddress/room/by-type?type=${type}",
`/room/by-type?type=${type}` -> `/room?type=${type}`

а еще лучше так: `/room?type={type}` (без доллара) и передавать type в качестве аргумента uriVariables

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/ReceptionClient.kt
> +        restTemplate.patchForObject<Room?>("$roomAddress/room/change-status?newStatus={status}", room, status)
если возвращаемое значение тебе не нужно, пиши так:

`patchForEntity<Void>`

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/ReceptionClient.kt
> +        restTemplate.patchForObject<Room?>("$roomAddress/room/change-status?newStatus={status}", room, status)
`$roomAddress/{number}?status={status}`

2022-04-10 09:01 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/service/client/RoomClient.kt
> +    @Value("\${room.storage.address}") private val roomStorage: String
это не используется

2022-04-10 09:01 UTC, mplain commented on src/main/resources/application.yaml
> +room.storage.address: http://localhost:5001
это не используется

2022-04-10 13:42 UTC, mplain requested changes

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    @GetMapping()
скобки не нужны

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    fun changeStatus(@PathVariable number: Int, @RequestBody status: String) {
не, в теле запроса надо передавать только json

статус как отдельный параметр лучше передавать в @RequestParam

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/HotelController.kt
> +    fun checkOut(@RequestParam number: Int) {
это не патчевые эндпоинты

суть патча не в том, будет или не будет внесено изменение в сущность

суть патча в том, что это эндпоинт для внесения конкретных изменений (в параметрах передается какие) в конкретный объект

если ты в /check-in не передаешь, какой объект и как патчить, а в /check-out говоришь какой объект, но не говоришь как его патчить

плюс у тебя контроллер не про комнаты (/rooms), а про отель (/hotel)

то есть судя по контроллеру и по его методам, это не эндпоинты для частичного изменения конкретных ресурсов / сущностей, а скорее эндпоинты для каких-то более общих действий, которые по касательной приведут к изменению каких-то сущностей

это больше похоже на POST

вот в RoomController ты уже изменяешь конкретные параметры конкретных ресурсов на конкретные новые значения - вот там это похоже на патч

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    fun changeStatus(@PathVariable number: Int, @RequestBody status: String) {
вот это похоже на патч - изменение конкретного параметра у конкретного ресурса на конкреное новое значение

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    fun getRoomByType(@RequestParam type: String): Set<Room> =
раз возвращает сет, но назови метод getRoomsByType (roomS, комнатЫ)

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/service/RoomService.kt
> +    fun getRoomByType(type: String): Set<Room> =
roomS

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/service/client/RoomDao.kt
> +        rooms.find { it.number == number }!!.status = newStatus
всегда старайся избегать !!, особенно в ситуациях когда действительно может вылететь ошибка - она будет крайне неинформативная

find + !! = first

get + !! = getValue

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/model/Room.kt
> +    var status: String
сделай энум
```
enum class Status { FREE, OCCUPIED }
```

можно прямо в этом же файле

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/RoomClient.kt
> +        null,
лучше ихбежать этот нулл, использовать такой синтаксис:
```
HttpMethod.GET, uriVariables = type
```

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/RoomClient.kt
> +            null
почему здесь трайкеч? попытка изменить статус несуществующей комнаты наверное должна возвращать ошибку, чтобы пользователь знал что что-то пошло не так? (и чтобы разработчик по логам тоже знал). а то здесь какая-то проблема возможна, но она будет просто замалчиваться - для такого нужно обоснование, рационализация

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/main/kotlin/ru/tinkoff/fintech/homework/Farm.kt
> -}
удали лишние файлы из мастера, чтобы они не засоряли каждый новый пулл реквест

2022-04-10 13:42 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/HotelController.kt
> +class HotelController(private val reception: Reception) {
вообще у тебя тут всё про отель, стоит наверное как-то иначе деление построить, в частности деление на пакеты, и на контроллеры в них

предлагаю следующее разделение:
- пакет reception, в нём ReceptionController ("/reception"), ReceptionService, RoomClient
- пакет room, в нём RoomController, RoomService, RoomDao
- пакет common, в нём пакет model, в нём Room

2022-04-10 14:09 UTC, AlexChampi commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/service/client/RoomClient.kt
> +        null,
когда я так пишу, exchange подчеркивается

2022-04-10 15:12 UTC, mplain requested changes

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/common/model/Room.kt
> +enum class Status {
ниже, после Room

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/common/model/Room.kt
> +class Room(
data class

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/ReceptionController.kt
> +@RequestMapping("/hotel")
/reception

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/Reception.kt
> +class Reception(private val roomClient: RoomClient) {
ReceptionService

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/client/RoomClient.kt
> +        restTemplate.patchForObject<Void>("$roomAddress/room/{number}", status, number)
`patchForEntity<Void>`

patchForObject не сработает вроде

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/client/RoomClient.kt
> +        restTemplate.patchForObject<Void>("$roomAddress/room/{number}", status, number)
ты здесь статус в теле передаешь чтоли? в теле запроса стоит передавать только json, голые строки лучше параметрами

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/RoomController.kt
> +    fun getRoomByType(@RequestParam type: String): Set<Room> =
getRoomsByType (roomS)

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/client/RoomClient.kt
> +        restTemplate.patchForObject<Void>("$roomAddress/room/{number}", status, number)
вижу что в RoomController  у тебя принимается не дело, а параметр

но здесь ты передаешь статус как тело

```
restTemplate.patchForEntity<Void>("$roomAddress$CHANGE_ROOM_STATUS", null, number, status)

private const val CHANGE_ROOM_STATUS = "/room/{number}?status={status}"
```

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/client/RoomClient.kt
> +        "$roomAddress/room?type={type}",
адреса эндпоинтов вынеси в константы

в самом низу этого файла, после тела класса
```
private const val GET_ROOMS_BY_TYPE = "/room?type={type}"
```

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/client/RoomClient.kt
> +            restTemplate.getForObject("$roomAddress/room/{number}", number)
адреса эндпоинтов вынеси в константы
```
private const val GET_ROOM = "/room/{number}"
```

2022-04-10 15:12 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/service/client/RoomDao.kt
> +        rooms.first().status = newStatus
ты здесь меняешь статус первой попавшейся комнате, по номеру не ищешь

2022-04-10 15:15 UTC, mplain requested changes

2022-04-10 15:15 UTC, mplain commented on src/test/kotlin/ru/tinkoff/fintech/homework/mockktest/HotelTest.kt
> +class HotelTest(private val mockMvc: MockMvc, private val objectMapper: ObjectMapper) : FeatureSpec() {
ReceptionTest

2022-04-10 16:05 UTC, mplain requested changes

2022-04-10 16:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/ReceptionService.kt
> +        result.forEach { requireNotNull(it) { "No such type of room" } }
у тебя клиент и так возвращает сет ненуллабельных комнат, этот чек не нужен

2022-04-10 16:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/client/RoomClient.kt
> +        restTemplate.patchForObject<Void>("$roomAddress$CHANGE_ROOM_STATUS", number, status)
ты передаешь number  в качестве тела запроса, а не параметра

добавь здесь явный null

2022-04-10 16:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/service/ReceptionService.kt
> +    fun getRoomByType(type: String): Set<Room> {
roomS

2022-04-10 16:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/room/service/client/RoomDao.kt
> +    fun getRoomByType(type: String): Set<Room> =
roomS

2022-04-10 16:05 UTC, mplain commented on src/test/kotlin/ru/tinkoff/fintech/homework/mockktest/ReceptionTest.kt
> +    private lateinit var roomDAO: RoomDao
roomDao

2022-04-10 16:05 UTC, mplain commented on src/test/kotlin/ru/tinkoff/fintech/homework/mockktest/ReceptionTest.kt
> +        every { roomClient.changeStatus(any(), any()) } answers { roomDAO.changeStatus(firstArg(), secondArg()) }
не надо мокировать клиент, пусть работает

2022-04-10 18:29 UTC, mplain requested changes

2022-04-10 18:29 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/homework/hotel/reception/ReceptionController.kt
> +    fun getRoomByType(@RequestParam type: String): Set<Room> =
roomS

2022-04-10 19:16 UTC, mplain approved these changes

2022-04-10 21:38 UTC, closed without merging